[Icon Theme]
Name=application
Comment=奈娜子密码本 icon theme

Directories=16x16/apps,32x32/apps,48x48/apps,128x128/apps,256x256/apps,scalable/actions,scalable/apps,scalable/categories,scalable/mimetypes,scalable/status

[16x16/apps]
Size=16
Type=Fixed
Context=Applications

[32x32/apps]
Size=32
Type=Fixed
Context=Applications

[48x48/apps]
Size=48
Type=Fixed
Context=Applications

[128x128/apps]
Size=128
Type=Fixed
Context=Applications

[scalable/actions]
Size=48
Type=Scalable
MinSize=1
MaxSize=256
Context=Actions

[scalable/apps]
Size=48
Type=Scalable
MinSize=1
MaxSize=256
Context=Applications

[scalable/categories]
Size=48
Type=Scalable
MinSize=1
MaxSize=256
Context=Categories

[scalable/mimetypes]
Size=48
Type=Scalable
MinSize=1
MaxSize=256
Context=MimeTypes

[scalable/status]
Size=48
Type=Scalable
MinSize=1
MaxSize=256
Context=Status

[256x256/apps]
Size=256
Type=Fixed
Context=Applications
